version: "3.8"
services:
  postgres:
    container_name: postgres_telegram_bot
    image: postgres:15
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - telegram-bot
    volumes:
      - $HOME/.database:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
  bot_app:
    build: .
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - telegram-bot
    depends_on:
      - postgres
networks:
  telegram-bot:
    external: false